services:
  app:
    build:
      context: .
      target: development
    volumes:
      - ./app.js:/app/app.js
      - ./public:/app/public
      - /app/node_modules
    command: ["npm", "run", "dev"]
